export const SLIME_FALLBACK_IMAGE = '/assets/slimes/common/slime_common_00_base.png'

export const SLIME_CLASS_LIST = [
  {
    id: 'common',
    nameKo: '공통',
    nameEn: 'Common',
    branches: [],
  },
  {
    id: 'warrior',
    nameKo: '전사',
    nameEn: 'Warrior',
    branches: [
      { id: 'sword', nameKo: '검 계열', nameEn: 'Sword' },
      { id: 'guardian', nameKo: '방패 계열', nameEn: 'Guardian' },
      { id: 'lancer', nameKo: '창 계열', nameEn: 'Lancer' },
    ],
  },
  {
    id: 'rogue',
    nameKo: '도적',
    nameEn: 'Rogue',
    branches: [
      { id: 'dagger', nameKo: '단검 계열', nameEn: 'Dagger' },
      { id: 'star', nameKo: '표창 계열', nameEn: 'Throwing Star' },
      { id: 'phantom', nameKo: '괴도 계열', nameEn: 'Phantom' },
    ],
  },
  {
    id: 'mage',
    nameKo: '마법사',
    nameEn: 'Mage',
    branches: [
      { id: 'fire', nameKo: '화염 계열', nameEn: 'Fire' },
      { id: 'frost', nameKo: '빙결 계열', nameEn: 'Frost' },
      { id: 'light', nameKo: '성광 계열', nameEn: 'Light' },
    ],
  },
  {
    id: 'archer',
    nameKo: '궁수',
    nameEn: 'Archer',
    branches: [
      { id: 'bow', nameKo: '장궁 계열', nameEn: 'Bow' },
      { id: 'crossbow', nameKo: '석궁 계열', nameEn: 'Crossbow' },
      { id: 'nature', nameKo: '자연 계열', nameEn: 'Nature' },
    ],
  },
]

export const SLIME_EVOLUTION_TREE = [
  {
    id: 'common',
    classId: 'common',
    nameKo: '공통',
    nameEn: 'Common',
    nodes: [
      {
        id: 'common-sprout',
        classId: 'common',
        branchId: null,
        stage: 0,
        nameKo: '새싹 슬라임',
        nameEn: 'Sprout Slime',
        unlockLevel: 1,
        image: '/assets/slimes/common/slime_common_00_base.png',
        description: '습관 여정을 막 시작한 작고 맑은 슬라임입니다.',
        statFocus: ['growth', 'energy'],
      },
      {
        id: 'common-adventurer',
        classId: 'common',
        branchId: null,
        stage: 0.5,
        nameKo: '초보 모험 슬라임',
        nameEn: 'Beginner Adventurer Slime',
        unlockLevel: 5,
        image: '/assets/slimes/common/slime_common_01_adventurer.png',
        description: '꾸준함을 배워 모험을 준비하는 초보 슬라임입니다.',
        statFocus: ['discipline', 'energy'],
      },
    ],
  },
  {
    id: 'warrior',
    classId: 'warrior',
    nameKo: '전사',
    nameEn: 'Warrior',
    nodes: [
      {
        id: 'warrior-trainee',
        classId: 'warrior',
        branchId: null,
        stage: 1,
        nameKo: '수련 전사',
        nameEn: 'Warrior Trainee',
        unlockLevel: 10,
        image: '/assets/slimes/warrior/slime_warrior_01_trainee.png',
        description: '기초 체력과 의지를 다지는 전사 슬라임입니다.',
        statFocus: ['strength', 'discipline'],
      },
    ],
    branches: [
      {
        id: 'sword',
        nameKo: '검 계열',
        nameEn: 'Sword',
        nodes: [
          {
            id: 'warrior-sword-blade-sprout',
            classId: 'warrior',
            branchId: 'sword',
            stage: 2,
            nameKo: '검의 맹아',
            nameEn: 'Blade Sprout',
            unlockLevel: 25,
            image: '/assets/slimes/warrior/slime_warrior_sword_02_blade_sprout.png',
            description: '검술의 싹을 틔운 공격형 전사 슬라임입니다.',
            statFocus: ['strength', 'focus'],
          },
          {
            id: 'warrior-sword-brave-knight',
            classId: 'warrior',
            branchId: 'sword',
            stage: 3,
            nameKo: '용맹 기사',
            nameEn: 'Brave Knight',
            unlockLevel: 40,
            image: '/assets/slimes/warrior/slime_warrior_sword_03_brave_knight.png',
            description: '정면 돌파와 꾸준한 루틴에 강한 기사 슬라임입니다.',
            statFocus: ['strength', 'vitality'],
          },
          {
            id: 'warrior-sword-sunblade-lord',
            classId: 'warrior',
            branchId: 'sword',
            stage: 4,
            nameKo: '태양검 군주',
            nameEn: 'Sunblade Lord',
            unlockLevel: 60,
            image: '/assets/slimes/warrior/slime_warrior_sword_04_sunblade_lord.png',
            description: '태양검의 힘으로 목표를 밀어붙이는 군주 슬라임입니다.',
            statFocus: ['strength', 'leadership'],
          },
        ],
      },
      {
        id: 'guardian',
        nameKo: '방패 계열',
        nameEn: 'Guardian',
        nodes: [
          {
            id: 'warrior-guardian-shield-guardian',
            classId: 'warrior',
            branchId: 'guardian',
            stage: 2,
            nameKo: '방패 수호자',
            nameEn: 'Shield Guardian',
            unlockLevel: 25,
            image: '/assets/slimes/warrior/slime_warrior_guardian_02_shield_guardian.png',
            description: '흔들림 없이 루틴을 지키는 방어형 슬라임입니다.',
            statFocus: ['vitality', 'discipline'],
          },
          {
            id: 'warrior-guardian-holy-guard',
            classId: 'warrior',
            branchId: 'guardian',
            stage: 3,
            nameKo: '성광 기사',
            nameEn: 'Holy Guard',
            unlockLevel: 40,
            image: '/assets/slimes/warrior/slime_warrior_guardian_03_holy_guard.png',
            description: '밝은 의지로 습관을 보호하는 수호 기사입니다.',
            statFocus: ['vitality', 'energy'],
          },
          {
            id: 'warrior-guardian-golden-wall-lord',
            classId: 'warrior',
            branchId: 'guardian',
            stage: 4,
            nameKo: '황금성벽 군주',
            nameEn: 'Golden Wall Lord',
            unlockLevel: 60,
            image: '/assets/slimes/warrior/slime_warrior_guardian_04_golden_wall_lord.png',
            description: '무너지지 않는 성벽처럼 꾸준함을 지키는 군주입니다.',
            statFocus: ['vitality', 'discipline'],
          },
        ],
      },
      {
        id: 'lancer',
        nameKo: '창 계열',
        nameEn: 'Lancer',
        nodes: [
          {
            id: 'warrior-lancer-spear-tracker',
            classId: 'warrior',
            branchId: 'lancer',
            stage: 2,
            nameKo: '창의 추적자',
            nameEn: 'Spear Tracker',
            unlockLevel: 25,
            image: '/assets/slimes/warrior/slime_warrior_lancer_02_spear_tracker.png',
            description: '멀리 있는 목표도 놓치지 않는 창술 슬라임입니다.',
            statFocus: ['focus', 'strength'],
          },
          {
            id: 'warrior-lancer-darkmoon-lancer',
            classId: 'warrior',
            branchId: 'lancer',
            stage: 3,
            nameKo: '암월 창기사',
            nameEn: 'Darkmoon Lancer',
            unlockLevel: 40,
            image: '/assets/slimes/warrior/slime_warrior_lancer_03_darkmoon_lancer.png',
            description: '밤에도 루틴을 추적하는 집요한 창기사입니다.',
            statFocus: ['focus', 'discipline'],
          },
          {
            id: 'warrior-lancer-blackstar-lord',
            classId: 'warrior',
            branchId: 'lancer',
            stage: 4,
            nameKo: '흑성창 군주',
            nameEn: 'Blackstar Lord',
            unlockLevel: 60,
            image: '/assets/slimes/warrior/slime_warrior_lancer_04_blackstar_lord.png',
            description: '검은 별의 창으로 긴 목표를 꿰뚫는 군주입니다.',
            statFocus: ['focus', 'strength'],
          },
        ],
      },
    ],
  },
  {
    id: 'rogue',
    classId: 'rogue',
    nameKo: '도적',
    nameEn: 'Rogue',
    nodes: [
      {
        id: 'rogue-shadow-apprentice',
        classId: 'rogue',
        branchId: null,
        stage: 1,
        nameKo: '그림자 견습생',
        nameEn: 'Shadow Apprentice',
        unlockLevel: 10,
        image: '/assets/slimes/rogue/slime_rogue_01_shadow_apprentice.png',
        description: '작은 습관을 빠르게 쌓아가는 민첩한 슬라임입니다.',
        statFocus: ['focus', 'gold'],
      },
    ],
    branches: [
      {
        id: 'dagger',
        nameKo: '단검 계열',
        nameEn: 'Dagger',
        nodes: [
          {
            id: 'rogue-dagger-dagger-tracker',
            classId: 'rogue',
            branchId: 'dagger',
            stage: 2,
            nameKo: '단검 추적자',
            nameEn: 'Dagger Tracker',
            unlockLevel: 25,
            image: '/assets/slimes/rogue/slime_rogue_dagger_02_dagger_tracker.png',
            description: '짧고 날카로운 집중으로 목표를 추적합니다.',
            statFocus: ['focus', 'gold'],
          },
          {
            id: 'rogue-dagger-phantom-rogue',
            classId: 'rogue',
            branchId: 'dagger',
            stage: 3,
            nameKo: '환영 도적',
            nameEn: 'Phantom Rogue',
            unlockLevel: 40,
            image: '/assets/slimes/rogue/slime_rogue_dagger_03_phantom_rogue.png',
            description: '흐트러짐 없이 조용히 루틴을 완수하는 도적입니다.',
            statFocus: ['focus', 'discipline'],
          },
          {
            id: 'rogue-dagger-nightshadow-lord',
            classId: 'rogue',
            branchId: 'dagger',
            stage: 4,
            nameKo: '밤그림자 군주',
            nameEn: 'Nightshadow Lord',
            unlockLevel: 60,
            image: '/assets/slimes/rogue/slime_rogue_dagger_04_nightshadow_lord.png',
            description: '어둠 속에서도 목표를 완수하는 그림자 군주입니다.',
            statFocus: ['focus', 'gold'],
          },
        ],
      },
      {
        id: 'star',
        nameKo: '표창 계열',
        nameEn: 'Throwing Star',
        nodes: [
          {
            id: 'rogue-star-star-wanderer',
            classId: 'rogue',
            branchId: 'star',
            stage: 2,
            nameKo: '표창 방랑자',
            nameEn: 'Star Wanderer',
            unlockLevel: 25,
            image: '/assets/slimes/rogue/slime_rogue_star_02_star_wanderer.png',
            description: '여러 습관을 가볍게 오가며 실천하는 슬라임입니다.',
            statFocus: ['focus', 'energy'],
          },
          {
            id: 'rogue-star-shadow-thrower',
            classId: 'rogue',
            branchId: 'star',
            stage: 3,
            nameKo: '그림자 투척수',
            nameEn: 'Shadow Thrower',
            unlockLevel: 40,
            image: '/assets/slimes/rogue/slime_rogue_star_03_shadow_thrower.png',
            description: '정확한 타이밍으로 습관을 완성하는 투척수입니다.',
            statFocus: ['focus', 'vitality'],
          },
          {
            id: 'rogue-star-starshadow-assassin',
            classId: 'rogue',
            branchId: 'star',
            stage: 4,
            nameKo: '별그림자 암살자',
            nameEn: 'Starshadow Assassin',
            unlockLevel: 60,
            image: '/assets/slimes/rogue/slime_rogue_star_04_starshadow_assassin.png',
            description: '별빛처럼 빠르게 핵심 목표를 끝내는 암살자입니다.',
            statFocus: ['focus', 'discipline'],
          },
        ],
      },
      {
        id: 'phantom',
        nameKo: '괴도 계열',
        nameEn: 'Phantom',
        nodes: [
          {
            id: 'rogue-phantom-treasure-tracker',
            classId: 'rogue',
            branchId: 'phantom',
            stage: 2,
            nameKo: '보물 추적자',
            nameEn: 'Treasure Tracker',
            unlockLevel: 25,
            image: '/assets/slimes/rogue/slime_rogue_phantom_02_treasure_tracker.png',
            description: '작은 성취를 보물처럼 모으는 추적자입니다.',
            statFocus: ['gold', 'focus'],
          },
          {
            id: 'rogue-phantom-illusion-thief',
            classId: 'rogue',
            branchId: 'phantom',
            stage: 3,
            nameKo: '환상 괴도',
            nameEn: 'Illusion Thief',
            unlockLevel: 40,
            image: '/assets/slimes/rogue/slime_rogue_phantom_03_illusion_thief.png',
            description: '유연하게 루틴을 이어가는 화려한 괴도입니다.',
            statFocus: ['gold', 'energy'],
          },
          {
            id: 'rogue-phantom-moonlight-thief-king',
            classId: 'rogue',
            branchId: 'phantom',
            stage: 4,
            nameKo: '월광 괴도왕',
            nameEn: 'Moonlight Thief King',
            unlockLevel: 60,
            image: '/assets/slimes/rogue/slime_rogue_phantom_04_moonlight_thief_king.png',
            description: '달빛 아래 보상을 거두는 괴도의 왕입니다.',
            statFocus: ['gold', 'focus'],
          },
        ],
      },
    ],
  },
  {
    id: 'mage',
    classId: 'mage',
    nameKo: '마법사',
    nameEn: 'Mage',
    nodes: [
      {
        id: 'mage-arcane-initiate',
        classId: 'mage',
        branchId: null,
        stage: 1,
        nameKo: '비전 견습생',
        nameEn: 'Arcane Initiate',
        unlockLevel: 10,
        image: '/assets/slimes/mage/slime_mage_01_arcane_initiate.png',
        description: '지식과 집중으로 성장하는 견습 마법사입니다.',
        statFocus: ['focus', 'crystals'],
      },
    ],
    branches: [
      {
        id: 'fire',
        nameKo: '화염 계열',
        nameEn: 'Fire',
        nodes: [
          {
            id: 'mage-fire-ember-scholar',
            classId: 'mage',
            branchId: 'fire',
            stage: 2,
            nameKo: '잿불 학자',
            nameEn: 'Ember Scholar',
            unlockLevel: 25,
            image: '/assets/slimes/mage/slime_mage_fire_02_ember_scholar.png',
            description: '작은 불씨처럼 공부와 실천을 이어갑니다.',
            statFocus: ['focus', 'energy'],
          },
          {
            id: 'mage-fire-flame-alchemist',
            classId: 'mage',
            branchId: 'fire',
            stage: 3,
            nameKo: '화염 연금술사',
            nameEn: 'Flame Alchemist',
            unlockLevel: 40,
            image: '/assets/slimes/mage/slime_mage_fire_03_flame_alchemist.png',
            description: '습관을 뜨거운 성과로 바꾸는 연금술사입니다.',
            statFocus: ['focus', 'crystals'],
          },
          {
            id: 'mage-fire-inferno-archsage',
            classId: 'mage',
            branchId: 'fire',
            stage: 4,
            nameKo: '지옥불 대현자',
            nameEn: 'Inferno Archsage',
            unlockLevel: 60,
            image: '/assets/slimes/mage/slime_mage_fire_04_inferno_archsage.png',
            description: '불굴의 집중력으로 목표를 태워 올리는 대현자입니다.',
            statFocus: ['focus', 'crystals'],
          },
        ],
      },
      {
        id: 'frost',
        nameKo: '빙결 계열',
        nameEn: 'Frost',
        nodes: [
          {
            id: 'mage-frost-frost-weaver',
            classId: 'mage',
            branchId: 'frost',
            stage: 2,
            nameKo: '서리 직조자',
            nameEn: 'Frost Weaver',
            unlockLevel: 25,
            image: '/assets/slimes/mage/slime_mage_frost_02_frost_weaver.png',
            description: '차분한 루틴을 촘촘하게 엮는 마법사입니다.',
            statFocus: ['discipline', 'focus'],
          },
          {
            id: 'mage-frost-tempest-magus',
            classId: 'mage',
            branchId: 'frost',
            stage: 3,
            nameKo: '폭풍 현자',
            nameEn: 'Tempest Magus',
            unlockLevel: 40,
            image: '/assets/slimes/mage/slime_mage_frost_03_tempest_magus.png',
            description: '흔들리는 날에도 집중을 유지하는 현자입니다.',
            statFocus: ['discipline', 'energy'],
          },
          {
            id: 'mage-frost-aurora-archsage',
            classId: 'mage',
            branchId: 'frost',
            stage: 4,
            nameKo: '오로라 대현자',
            nameEn: 'Aurora Archsage',
            unlockLevel: 60,
            image: '/assets/slimes/mage/slime_mage_frost_04_aurora_archsage.png',
            description: '차분함과 통찰로 긴 성장을 완성하는 대현자입니다.',
            statFocus: ['discipline', 'crystals'],
          },
        ],
      },
      {
        id: 'light',
        nameKo: '성광 계열',
        nameEn: 'Light',
        nodes: [
          {
            id: 'mage-light-dawn-acolyte',
            classId: 'mage',
            branchId: 'light',
            stage: 2,
            nameKo: '여명의 사제',
            nameEn: 'Dawn Acolyte',
            unlockLevel: 25,
            image: '/assets/slimes/mage/slime_mage_light_02_dawn_acolyte.png',
            description: '새벽처럼 하루를 밝히는 회복형 슬라임입니다.',
            statFocus: ['energy', 'discipline'],
          },
          {
            id: 'mage-light-starhealer',
            classId: 'mage',
            branchId: 'light',
            stage: 3,
            nameKo: '별빛 치유사',
            nameEn: 'Starhealer',
            unlockLevel: 40,
            image: '/assets/slimes/mage/slime_mage_light_03_starhealer.png',
            description: '꾸준함으로 지친 에너지를 회복하는 치유사입니다.',
            statFocus: ['energy', 'crystals'],
          },
          {
            id: 'mage-light-celestial-high-priest',
            classId: 'mage',
            branchId: 'light',
            stage: 4,
            nameKo: '천상의 대사제',
            nameEn: 'Celestial High Priest',
            unlockLevel: 60,
            image: '/assets/slimes/mage/slime_mage_light_04_celestial_high_priest.png',
            description: '하늘빛 루틴으로 성장을 이끄는 대사제입니다.',
            statFocus: ['energy', 'crystals'],
          },
        ],
      },
    ],
  },
  {
    id: 'archer',
    classId: 'archer',
    nameKo: '궁수',
    nameEn: 'Archer',
    nodes: [
      {
        id: 'archer-forest-shooter',
        classId: 'archer',
        branchId: null,
        stage: 1,
        nameKo: '숲길 사수',
        nameEn: 'Forest Shooter',
        unlockLevel: 10,
        image: '/assets/slimes/archer/slime_archer_01_forest_shooter.png',
        description: '멀리 있는 목표를 꾸준히 겨냥하는 사수입니다.',
        statFocus: ['focus', 'vitality'],
      },
    ],
    branches: [
      {
        id: 'bow',
        nameKo: '장궁 계열',
        nameEn: 'Bow',
        nodes: [
          {
            id: 'archer-bow-wind-shooter',
            classId: 'archer',
            branchId: 'bow',
            stage: 2,
            nameKo: '바람 사수',
            nameEn: 'Wind Shooter',
            unlockLevel: 25,
            image: '/assets/slimes/archer/slime_archer_bow_02_wind_shooter.png',
            description: '가벼운 흐름으로 습관을 이어가는 장궁 슬라임입니다.',
            statFocus: ['focus', 'energy'],
          },
          {
            id: 'archer-bow-gale-ranger',
            classId: 'archer',
            branchId: 'bow',
            stage: 3,
            nameKo: '질풍 순찰자',
            nameEn: 'Gale Ranger',
            unlockLevel: 40,
            image: '/assets/slimes/archer/slime_archer_bow_03_gale_ranger.png',
            description: '빠르고 정확하게 목표를 순찰하는 궁수입니다.',
            statFocus: ['focus', 'vitality'],
          },
          {
            id: 'archer-bow-tempest-bow-lord',
            classId: 'archer',
            branchId: 'bow',
            stage: 4,
            nameKo: '폭풍궁 군주',
            nameEn: 'Tempest Bow Lord',
            unlockLevel: 60,
            image: '/assets/slimes/archer/slime_archer_bow_04_tempest_bow_lord.png',
            description: '폭풍처럼 강한 집중으로 목표를 관통하는 군주입니다.',
            statFocus: ['focus', 'strength'],
          },
        ],
      },
      {
        id: 'crossbow',
        nameKo: '석궁 계열',
        nameEn: 'Crossbow',
        nodes: [
          {
            id: 'archer-crossbow-mechanic-crossbowman',
            classId: 'archer',
            branchId: 'crossbow',
            stage: 2,
            nameKo: '기계 석궁수',
            nameEn: 'Mechanic Crossbowman',
            unlockLevel: 25,
            image: '/assets/slimes/archer/slime_archer_crossbow_02_mechanic_crossbowman.png',
            description: '정교한 시스템으로 습관을 관리하는 석궁수입니다.',
            statFocus: ['discipline', 'focus'],
          },
          {
            id: 'archer-crossbow-precision-sniper',
            classId: 'archer',
            branchId: 'crossbow',
            stage: 3,
            nameKo: '정밀 저격수',
            nameEn: 'Precision Sniper',
            unlockLevel: 40,
            image: '/assets/slimes/archer/slime_archer_crossbow_03_precision_sniper.png',
            description: '정확한 계획으로 목표를 하나씩 완수합니다.',
            statFocus: ['discipline', 'focus'],
          },
          {
            id: 'archer-crossbow-starpiercer',
            classId: 'archer',
            branchId: 'crossbow',
            stage: 4,
            nameKo: '별꿰뚫는 명사수',
            nameEn: 'Starpiercer',
            unlockLevel: 60,
            image: '/assets/slimes/archer/slime_archer_crossbow_04_starpiercer.png',
            description: '별처럼 먼 장기 목표도 꿰뚫는 명사수입니다.',
            statFocus: ['discipline', 'focus'],
          },
        ],
      },
      {
        id: 'nature',
        nameKo: '자연 계열',
        nameEn: 'Nature',
        nodes: [
          {
            id: 'archer-nature-vine-hunter',
            classId: 'archer',
            branchId: 'nature',
            stage: 2,
            nameKo: '덩굴 사냥꾼',
            nameEn: 'Vine Hunter',
            unlockLevel: 25,
            image: '/assets/slimes/archer/slime_archer_nature_02_vine_hunter.png',
            description: '자연스럽게 이어지는 루틴을 사냥하는 슬라임입니다.',
            statFocus: ['vitality', 'energy'],
          },
          {
            id: 'archer-nature-spirit-pathfinder',
            classId: 'archer',
            branchId: 'nature',
            stage: 3,
            nameKo: '정령 길잡이',
            nameEn: 'Spirit Pathfinder',
            unlockLevel: 40,
            image: '/assets/slimes/archer/slime_archer_nature_03_spirit_pathfinder.png',
            description: '습관의 길을 찾고 에너지를 회복하는 길잡이입니다.',
            statFocus: ['vitality', 'energy'],
          },
          {
            id: 'archer-nature-ancient-forest-sage',
            classId: 'archer',
            branchId: 'nature',
            stage: 4,
            nameKo: '고대숲 궁현자',
            nameEn: 'Ancient Forest Sage',
            unlockLevel: 60,
            image: '/assets/slimes/archer/slime_archer_nature_04_ancient_forest_sage.png',
            description: '오래 지속되는 습관의 숲을 지키는 궁현자입니다.',
            statFocus: ['vitality', 'discipline'],
          },
        ],
      },
    ],
  },
]

export function getEvolutionClassById(classId) {
  return SLIME_CLASS_LIST.find((classItem) => classItem.id === classId) ?? null
}

export function getAllEvolutionNodes() {
  return SLIME_EVOLUTION_TREE.flatMap((classTree) => [
    ...(classTree.nodes ?? []),
    ...(classTree.branches ?? []).flatMap((branch) => branch.nodes ?? []),
  ])
}

export function getEvolutionNodeById(nodeId) {
  return getAllEvolutionNodes().find((node) => node.id === nodeId) ?? null
}
